variable "region" {}
variable "vpc_cidr_block" {}
variable "vpc_tag" {}
variable "subnet_cidr_block" {}
variable "subnet_az" {}
variable "subnet_tag" {}
variable "igw-tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ami" {}
variable "ec2_az" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_tag" {}